#!/bin/bash

WWWROOT=/var/www/html
source /etc/xsce/xsce.env

MENUDIR=$WWWROOT/iiab-menu
mkdir -p $MENUDIR

mkdir -p $MENUDIR/local/menu-defs
mkdir -p $MENUDIR/local/html

rsync -av common $WWWROOT
rsync -av menu-files $MENUDIR
rsync -av samples $MENUDIR

# copy sample index file if none exists
if [ ! -e $MENUDIR/index.html ]; then
    cp samples/index-all.html $MENUDIR/index.html
fi

# restore modified files from local
cp -rf $MENUDIR/local/* $MENUDIR/menu-files

echo 'files copied'

# Check for user and create if absent
rc=`mysql --execute "SELECT Password FROM mysql.user where Host = 'localhost' and User = 'iiab_commenter';"`

if [ "$rc" = "" ]; then
  mysql --execute "CREATE USER iiab_commenter@localhost IDENTIFIED BY 'g0adm1n';"
fi

# Create database and table
mysql < setup/comments-db.sql

echo 'database created'
